version: "2"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
  wiki:
    build: wiki/docker-mediawiki
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./wiki/conf:/var/www-shared/html
    links:
      - mysql
    environment:
      DOCKER_HOST: $DOCKER_HOST
    restart: unless-stopped
  parsoid:
    build: wiki/docker-parsoid
    ports:
      - "8142:8142"
    volumes:
      - ./wiki/parsoid-data:/data
    environment:
        MW_HOST: wiki
        PORT: 8142
    restart: unless-stopped
  wordpress:
    build: wordpress/docker-wordpress
    depends_on:
      - mysql
    ports:
      - "8081:80"
    volumes:
      - ./wordpress/conf:/var/www-shared/html
    links:
      - mysql
    environment:
      DOCKER_HOST: $DOCKER_HOST
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    restart: unless-stopped
  nginx:
    image: nginx:1.11.4
    depends_on:
      - wiki
      - wordpress
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
volumes:
  mysql-data:
    external: true

