version: "2"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  wiki:
    build: docker-mediawiki
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./conf:/var/www-shared/html
    links:
      - mysql
    environment:
      DOCKER_HOST: $DOCKER_HOST
  parsoid:
    build: docker-parsoid
    ports:
      - "8142:8142"
    volumes:
      - ./parsoid-data:/data
    environment:
        MW_HOST: wiki
        PORT: 8142
volumes:
  mysql-data:
    external: true
