version: "2"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  wiki:
    build: docker-mediawiki
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./conf:/var/www-shared/html
    links:
      - mysql
volumes:
  mysql-data:
    external: true
